name: Build

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "main2"]
  pull_request:  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
